### ISSUE TITLE
Github Issue Template 등록

### ISSUE THREAD

**Issue by Moon-GD** [softeerbootcamp/Team6-Oil-Pocket#105]
## 👨‍💻 담당자
- 문경덕

<br>

## ❗️ 해야 할 일
- [x] Github Issue Template 등록

<br>

## ⏰ 예상 타임 라인
- 02.08 ~ 02. 09

<br>

## 리뷰어 요구 사항
- 2월 9일 오전 스크럼, 스프린트 때 확인 후 피드백 부탁드립니다.

**Comment by jaewonjjang** [comment]
확인했습니다. 추후 용량 초과되는 문제에 대해 얘기해보면 좋을 것 같습니다.
