### ISSUE TITLE
검색, 지도 뷰 제작

### ISSUE THREAD

**Issue by jaewonjjang** [softeerbootcamp/Team6-Oil-Pocket#12]
- 초기에는 현재 위치와 현재 위치 주변 주유소(마커 + 리스트) 출력
- 검색 옵션 선택시 출발지, 도착지 입력 후 경로 내에 존재하는 주유소(마커 + 리스트) 출력
- 출발지 도착지 입력 시 검색창에 있는 값으로 자동 검색 기능(입력마다 재검색)

**Comment by jaewonjjang** [comment]
코드 마이그레이션 필요
함수형 프로그래밍 방식으로 코드 분리 필요
필요 없는 변수들 삭제
지도 UI에 추가할 사항 있는지 확인

**Comment by Moon-GD** [comment]
해당 이슈는 <a href="https://github.com/softeerbootcamp/Team6-Oil-Pocket/issues/34">34번</a>과 합쳐져 <a href="https://github.com/softeerbootcamp/Team6-Oil-Pocket/issues/101">101번째</a> 이슈로 재개설되었습니다./
