### ISSUE TITLE
마이페이지 기름 입력 공간 이벤트 추가

### ISSUE THREAD

**Issue by Moon-GD** [softeerbootcamp/Team6-Oil-Pocket#122]
## 👨‍💻 담당자
- 문경덕

<br>

## ❗️ 해야 할 일
- [x] 기름 선택 input box -> 선택지 형으로 변경
- [x] 기름 선택지 이벤트 추가
- [x] 기름 입력 파싱 이벤트
- [x] 기름 입력에 따른 애니메이션 추가
- [x] 주유소 input box -> 검색 선택지형으로 변경

<br>

## ⏰ 예상 타임 라인
- 02.11 ~ 02. 12

**Comment by Moon-GD** [comment]
팀원 모두에게 공유하였습니다.

https://user-images.githubusercontent.com/74173976/218309599-940529fb-be30-49dc-b35c-0a90c3f4a42f.mov

**Comment by jaewonjjang** [comment]
주유소 검색 기능 추가하고 추후 통신 연결하여 차트 완성하면 좋을 것 같습니다.
