### ISSUE TITLE
마이페이지 - 월별 비교 페이지 이벤트 추가

### ISSUE THREAD

**Issue by Moon-GD** [softeerbootcamp/Team6-Oil-Pocket#128]
## 👨‍💻 담당자
- 문경덕

<br>

## ❗️ 해야 할 일
- [x] 차트 생성 함수 추가
- [x] 차트 생성 이벤트 추가
- [x] 범례를 통한 필터 이벤트 추가
- [x] 차트 디자인

<br>

## ⏰ 예상 타임 라인
- 02.12 ~ 02. 12

**Comment by jaewonjjang** [comment]
차트 확인했습니다. 추후 주유소 검색 추가해서 반영하겠습니다.
