### ISSUE TITLE
마이페이지 - 이번 달 비교 페이지 이벤트 추가

### ISSUE THREAD

**Issue by Moon-GD** [softeerbootcamp/Team6-Oil-Pocket#130]
## 👨‍💻 담당자
- 문경덕

<br>

## ❗️ 해야 할 일
- [x] money string 3자리씩 끊어서 쉼표 추가
- [x] 가격에 따라 다른 이미지 출력
- [x] 가격에 따라 다른 글귀 출력

<br>

## ⏰ 예상 타임 라인
- 02.12 ~ 02. 12 (하기 전엔 안 잔다)

**Comment by jaewonjjang** [comment]
확인했습니다!! 나중에 애니메이션 더 추가할거 있으면 같이 살펴보면 좋을것 같아요 ㅎㅎ
