### ISSUE TITLE
코드 피드백

### ISSUE THREAD

**Issue by crongro** [softeerbootcamp/Team6-Oil-Pocket#139]
- ~~common/function.js 보다는 /common/utils.js 라고 해도 될 듯.  유틸은 만든건 좋아요.~~
→ 수정 완료! (문경덕)

- ~~URL같은 경우는 variable.js 내에서 선언하신것 좋고요. 별도 env등에 적어도 되고요.(참고)~~
→ 수정 완료! (문경덕)

- ~~pipe 시도하신코드가 pipe(()=>foo(), ()=> bar,) 이런식인데요 이렇게 하면 더 좋을듯해요~~
   ~~pipe(foo, bar)();~~
→ 참고 완료! (문경덕)

- forEach등의 고차함수 콜백도 함수를 분리해서 선언해보세요.

- ~~document.querySelector 처럼 괜히 긴데 자주 쓰는코드도 유틸로 만들어보세요. ([참고](https://gist.github.com/AllThingsSmitty/f9029e6236a7c2a03203))~~
→ 수정 완료! (문경덕)

- ~~myPage/chart/template.js 안에 반복적인 코드가 보이는데 이는 template literal 에서 반복문으로 표현하시면 좋겠어요.~~
→ 수정 완료! (문경덕)

- createElement, appendChild를 사용하는것도 좋은데 template literal을 바로 사용하면 더 편리하게 DOM작업을 하고 코드도 더 보기 좋을거 같아요. 

- register/event.js 안에 조건문처럼 긴 코드는 더 작은 함수여러개로 분리할 수도 있을듯.

- ~~fetch 요청시 await 사용해보기.~~
→ 수정 완료! (문경덕)

- response  status 는 200. 201 이외 다른 상황에 대한 대처도 고민해보기.

- 지금 js/모든 폴더가 여러개 있는데요, 만약 계층적인 구조로 폴더를 구성할 수 있다면 그렇게 해보세요. 

열심히 개발중이신것 같아서 좋네요.

**Comment by gyuturn** [comment]
피드백 감사합니다!
