### ISSUE TITLE
마이페이지 주유 기록 입력 통신

### ISSUE THREAD

**Issue by Moon-GD** [softeerbootcamp/Team6-Oil-Pocket#140]
## 👨‍💻 담당자
- 문경덕, 김규민

<br>

## ❗️ 해야 할 일
- [x] 주유소 검색 API 연결
- [x] 주유 입력 API 연결

<br>

## ⏰ 예상 타임 라인
- 02.12 ~ 02. 12

**Comment by gyuturn** [comment]
확인
