### ISSUE TITLE
마이페이지 이번 달 분석 통신

### ISSUE THREAD

**Issue by Moon-GD** [softeerbootcamp/Team6-Oil-Pocket#153]
## 👨‍💻 담당자
- 문경덕, 박원종

<br>

## ❗️ 해야 할 일
- [x] 이번 달 분석 통신 API 연결
- [x] 도커 재배포
- [x] 해당 페이지 이벤트 추가

<br>

## ⏰ 예상 타임 라인
- 02.14 ~ 02. 14

**Comment by ajongs** [comment]
api 연결하시느라 수고하셨습니당~
