### ISSUE TITLE
로그인 / 회원가입 통신 연결

### ISSUE THREAD

**Issue by Moon-GD** [softeerbootcamp/Team6-Oil-Pocket#16]
## @Moon-GD  TODO
- [x] 로그인 api 명세서 확정
- [x] 회원가입 api 명세서 확정
- [x] 로그인 통신 연결

## @gyuturn 
- [x] 로그인, 회원가입, 중복 아이디 체크 예외처리 프론트와 협의
- [x] 로그아웃 회원탈퇴 API(시간이 된다면 구현)

**Comment by gyuturn** [comment]
백엔드 어플리케이션 로컬에서 구동 예정
