### ISSUE TITLE
[FE] 피드백

### ISSUE THREAD

**Issue by crongro** [softeerbootcamp/Team6-Oil-Pocket#37]
아니 디렉토리 이름에 사람 이름이...ㅎ. 

test.js는 테스트라 안보려다가 봤는데 누가 짜논 jquery 기반 코드 같은데.. 잘 마이그레이션 해서 사용하세요.

커밋에 왜 node_modules디렉토리가 되어 있죠? gitignore 추가해서 커밋에서 제외하세요.

화이팅입니다!

**Comment by Moon-GD** [comment]
감사합니다 바로 반영하도록 하겠습니다!!

**Comment by Moon-GD** [comment]
최재원님께 이슈 공유 후 추후 계획 수립하였습니다.
